"""
src/ai/analyzer.py
------------------
Uses the Anthropic Claude API to validate trading signals.

Before executing any trade, we send Claude:
  - The signal (buy/sell, symbol, strategy reasoning)
  - Recent price action (last 5 days of OHLCV)
  - Recent % change and volume trend

Claude returns a confidence score (0–1) and reasoning.
We only execute trades where confidence >= threshold (default: 0.70).

This is the AI "second opinion" layer that filters out weak signals
and is the key to pushing win rate toward 75%+.
"""

import logging
import json
from dataclasses import dataclass
from anthropic import Anthropic

from config.settings import AIConfig

logger = logging.getLogger(__name__)


@dataclass
class AIAnalysis:
    """Result from the AI signal review."""
    confidence: float       # 0.0 to 1.0
    reasoning: str          # Human-readable explanation
    risk_factors: list      # List of identified risks
    recommended_action: str # "EXECUTE", "SKIP", or "REDUCE_SIZE"


class AIAnalyzer:
    """
    Claude-powered trade signal validator.

    Sends each candidate trade to Claude for analysis.
    Returns a confidence score and reasoning.
    """

    def __init__(self, config: AIConfig):
        self.config = config
        self.client = Anthropic(api_key=config.api_key)
        logger.info("AI Analyzer initialized (Claude)")

    def analyze_signal(self, signal, schwab_client) -> AIAnalysis:
        """
        Main method: analyze a trade signal and return AI assessment.

        Args:
            signal: TradeSignal object from a strategy
            schwab_client: For fetching additional market context

        Returns:
            AIAnalysis with confidence score and reasoning
        """
        # Fetch recent price history for context
        try:
            candles = schwab_client.get_price_history(
                symbol=signal.symbol,
                period_type="day",
                period=self.config.context_lookback_days,
                frequency_type="minute",
                frequency=30,  # 30-minute candles
            )
            price_summary = self._summarize_candles(candles)
        except Exception as e:
            logger.warning(f"Could not fetch price history for AI context: {e}")
            price_summary = "Price history unavailable"

        # Build the prompt
        prompt = self._build_prompt(signal, price_summary)

        # Call Claude
        try:
            response = self.client.messages.create(
                model=self.config.model,
                max_tokens=1000,
                system=self._system_prompt(),
                messages=[{"role": "user", "content": prompt}],
            )

            # Parse Claude's JSON response
            raw = response.content[0].text
            return self._parse_response(raw)

        except Exception as e:
            logger.error(f"AI analysis failed: {e}")
            # On failure, return low-confidence to be safe (fail closed)
            return AIAnalysis(
                confidence=0.0,
                reasoning=f"AI analysis failed: {e}",
                risk_factors=["AI unavailable"],
                recommended_action="SKIP",
            )

    def _system_prompt(self) -> str:
        return """You are an expert stock and options trader with 20 years of experience.
Your job is to review trading signals generated by algorithmic strategies and assess their quality.

You must respond ONLY with a valid JSON object in this exact format:
{
  "confidence": 0.75,
  "reasoning": "Brief explanation of why this trade looks good or bad",
  "risk_factors": ["list", "of", "risks"],
  "recommended_action": "EXECUTE"
}

Rules:
- confidence: float between 0.0 and 1.0
- recommended_action: one of "EXECUTE", "SKIP", or "REDUCE_SIZE"
- Be conservative. A bad skip is better than a bad trade.
- Consider: trend direction, volume, recent news sentiment, support/resistance
- If the market is choppy or uncertain, return low confidence
"""

    def _build_prompt(self, signal, price_summary: str) -> str:
        return f"""Please analyze this trading signal:

SIGNAL DETAILS:
- Symbol: {signal.symbol}
- Direction: {signal.direction} (BUY or SELL)
- Strategy: {signal.strategy_name}
- Entry Price: ${signal.entry_price:.2f}
- Stop Loss: ${signal.stop_loss:.2f} ({signal.stop_loss_pct:.1%} risk)
- Take Profit: ${signal.take_profit:.2f} ({signal.take_profit_pct:.1%} target)
- Asset Type: {signal.asset_type}
- Strategy Reasoning: {signal.reasoning}

RECENT PRICE ACTION (last 5 days):
{price_summary}

Should I execute this trade? Respond with JSON only."""

    def _summarize_candles(self, candles: list) -> str:
        """Convert raw candle data into a readable summary for the AI."""
        if not candles:
            return "No data available"

        # Take last 10 candles max to keep prompt short
        recent = candles[-10:]
        lines = []
        for c in recent:
            lines.append(
                f"  Open: ${c['open']:.2f} | High: ${c['high']:.2f} | "
                f"Low: ${c['low']:.2f} | Close: ${c['close']:.2f} | "
                f"Vol: {c['volume']:,}"
            )

        # Compute overall trend
        if len(candles) >= 2:
            first_close = candles[0]["close"]
            last_close = candles[-1]["close"]
            change = (last_close - first_close) / first_close
            trend = f"Overall trend: {change:+.1%} over {len(candles)} candles"
        else:
            trend = "Insufficient data for trend"

        return trend + "\n" + "\n".join(lines)

    def _parse_response(self, raw: str) -> AIAnalysis:
        """Parse Claude's JSON response into an AIAnalysis object."""
        # Strip markdown code fences if present
        clean = raw.strip()
        if clean.startswith("```"):
            clean = clean.split("```")[1]
            if clean.startswith("json"):
                clean = clean[4:]
        clean = clean.strip()

        data = json.loads(clean)
        return AIAnalysis(
            confidence=float(data.get("confidence", 0.0)),
            reasoning=data.get("reasoning", ""),
            risk_factors=data.get("risk_factors", []),
            recommended_action=data.get("recommended_action", "SKIP"),
        )
